# Site settings
title: AkiraChix
email: dev@ocupop.com
url: "http://akirachix.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code:


# Collections
collections:
  examples:
    output: true
    layout: default
    permalink: /examples/:path/

# defaults:
#   -
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

